seed: 42

device: auto # auto | cuda | cuda:0 | mps | cpu

dtype: fp32  # fp32 | fp16 | bf16

model:
  vocab_size: 64000
  d_model: 512
  n_head: 8
  d_ff: 2048
  n_layer: 6
  batch_size: 16
  seq_len: 256
  max_len: 1024

block:
  norm: prenorm
  prenorm:
    resid_scale: none
  postnorm:
    block_dropout: 0.0
  norm_eps: 1e-5
  attn:
    bias: true
    dropout: 0.0
    out_dropout: 0.0
  ffn:
    activation: gelu
    dropout: 0.0

optim:
  name: adamw
  lr: 3e-4
  weight_decay: 0.1
  betas: [0.9, 0.95]
  grad_clip: 1.0
  sched: cosine
  warmup_ratio: 0.01